// Generated by CoffeeScript 1.6.2
(function() {
  jQuery(function() {
    var $, $environmentIndicator, $user_list, eiSettings, linkHoverIn, linkHoverOut, listHoverIn, listHoverOut, onTimeout, timeout;

    $ = jQuery;
    window.environmentIndicator = $.extend({
      text: ' ',
      color: '#006400',
      position: 'left',
      ul_enabled: true,
      users: '',
      assetsPath: '/'
    }, window.environmentIndicator);
    eiSettings = window.environmentIndicator;
    if ($('body:not(.environment-indicator-processed)').length) {
      eiSettings.cssClass = 'environment-indicator-' + eiSettings.position;
      if (!$('#environment-indicator').length) {
        $('body').prepend('<div id="environment-indicator">' + eiSettings.text + '</div>');
        $('body').addClass(eiSettings.cssClass);
        $environmentIndicator = $('#environment-indicator');
        $environmentIndicator.css('background-color', eiSettings.color);
        $environmentIndicator.html('<div style="margin-top:100px">' + $environmentIndicator.text().replace(/(.)/g, "$1<br />") + '</div>');
        if (eiSettings.ul_enabled && eiSettings.users) {
          $user_list = "<div id=\"ei-ul-wrapper\">\n  <div id=\"ei-ul-button\">\n  </div>\n  <div id=\"ei-ul-inner-wrapper\">\n    <div id=\"ei-ul-arrow\">\n    </div>\n    <div id=\"ei-ul-list-wrapper\">\n      <div id=\"ei-ul-border\">\n        <div id=\"ei-ul-bg\">\n        </div>\n      </div>\n    </div>\n  </div>\n</div>";
          $environmentIndicator.html($user_list + $environmentIndicator.html());
          $('#ei-ul-button').attr('title', 'Click to show users list.');
          $('#ei-ul-bg').html('<div id="ei-ul-login">' + 'Login as:' + '</div><ul>' + eiSettings.users + '</ul>');
          $('#ei-ul-button').css('background-image', 'url(\'' + eiSettings.assetsPath + '/lock-button.png\')');
          $('#ei-ul-border').css('background-image', 'url(\'' + eiSettings.assetsPath + '/transparent.png\')');
          $('#ei-ul-list-wrapper').css('background-color', eiSettings.color);
          $('#ei-ul-bg').css('background-color', eiSettings.color);
          timeout = null;
          onTimeout = function() {
            jQuery('#ei-ul-inner-wrapper').removeClass('ei-ul-inner-wrapper-visible');
            return jQuery('#ei-ul-button').removeClass('ei-ul-button-pushed');
          };
          $('#ei-ul-button').click(function() {
            $('#ei-ul-inner-wrapper').toggleClass('ei-ul-inner-wrapper-visible');
            $('#ei-ul-button').toggleClass('ei-ul-button-pushed');
            if ($('#ei-ul-button').hasClass('ei-ul-button-pushed')) {
              return timeout = setTimeout(onTimeout, 5000);
            }
          });
          linkHoverIn = function() {
            return $(this).parent().css('background-image', 'url(\'' + eiSettings.assetsPath + '/transparent.png\')');
          };
          linkHoverOut = function() {
            return $(this).parent().css('background-image', 'none');
          };
          $("#ei-ul-list-wrapper ul li a").hover(linkHoverIn, linkHoverOut);
          listHoverIn = function() {
            if (timeout) {
              return clearTimeout(timeout);
            }
          };
          listHoverOut = function() {
            return timeout = setTimeout(onTimeout, 2000);
          };
          $('#ei-ul-list-wrapper').hover(listHoverIn, listHoverOut);
          if (eiSettings.position === 'left') {
            $('#ei-ul-inner-wrapper').addClass('ei-ul-inner-wrapper-left');
            $('#ei-ul-arrow').addClass('ei-ul-arrow-left');
            $('#ei-ul-arrow').css('border-right', '12px solid ' + eiSettings.color);
          } else {
            $('#ei-ul-inner-wrapper').addClass('ei-ul-inner-wrapper-right');
            $('#ei-ul-arrow').addClass('ei-ul-arrow-right');
            $('#ei-ul-arrow').css('border-left', '12px solid ' + eiSettings.color);
          }
        }
      }
      return $('body:not(.environment-indicator-processed)').addClass('environment-indicator-processed');
    }
  });

}).call(this);
